---
spring:
  application:
    name: greeting-service
greeting-service:
    greeting: "Ciao"
    default-value: "mundo"
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8888
